import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
const login = fs.readFileSync(path.join(root, "public", "login.html"), "utf8");
const publicApi = fs.readFileSync(path.join(root, "api", "public-dashboard.js"), "utf8");
const middleware = fs.readFileSync(path.join(root, "middleware.js"), "utf8");
assert.match(html, /전체 남은 크레딧/);
assert.match(html, /공급자별 크레딧/);
assert.match(html, /최근 GPU 작업/);
assert.match(html, /의미 있는 비용 기록/);
assert.match(html, /데이터 출처/);
assert.match(html, /skeleton-card/);
assert.doesNotMatch(html, /PubMed|Work Memory|스토리지 관리/);
assert.match(app, /\/api\/public-dashboard/);
assert.doesNotMatch(app, /\/api\/(usage|jobs)/);
assert.match(app, /Math\.round\(usage\.remaining\.naver\)/);
assert.match(app, /usage\.expiry/);
assert.match(publicApi, /CREDIT_EXPIRY/);
assert.match(publicApi, /cleanup_verified/);
assert.doesNotMatch(publicApi, /command:\s*job\.command|id:\s*job\.id|error:\s*job\.error/);
assert.match(middleware, /\/api\/public-dashboard/);
assert.match(html, /WELLNESSBOX/);
assert.match(login, /비밀번호가 올바르지 않아요/);
console.log("dashboard contract tests passed");
