import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const models = readFileSync(new URL("../lib/models.js", import.meta.url), "utf8");
assert.ok(models.includes('const KEY = "control/models.json"'), "model registry must be independent from rolling job history");
assert.ok(models.includes("getPlaygroundPreset(job.preset_id)"), "model registration must use the shared preset contract");
assert.ok(models.includes("allowPartial") && models.includes('preset?.kind === "image"'), "checkpointed image runs must be recoverable after interruption");
assert.ok(models.includes("artifact_key: job.result_key"), "registered model must retain its immutable Object Storage artifact");
assert.ok(models.includes("training_job_id: job.id"), "model must be traceable to training evidence");
assert.ok(models.includes("parent_model_id: job.source_model_id"), "continued training must retain model lineage");
assert.ok(models.includes("checkpoints"), "registered image models must expose checkpoint steps");
assert.ok(models.includes("preview_key: completed ? job.preview_key : undefined"), "interrupted versions must not display stale parent previews");
assert.ok(models.includes('metadata?.training_state === "completed"'), "completed training metadata must survive a later preview failure");
assert.ok(models.includes("models[index] = refreshed"), "existing checkpoint models must be refreshable after recovery");
const presets = readFileSync(new URL("../lib/playground-presets.js", import.meta.url), "utf8");
for (const marker of ['"qwen-lora-v1"', '"sdxl-lora-v1"', 'kind: "image"', "sanitizeModelMetadata"]) assert.ok(presets.includes(marker), `preset contract missing ${marker}`);
const callback = readFileSync(new URL("../api/worker-callback.js", import.meta.url), "utf8");
assert.ok(callback.includes("registerModel(job"), "terminal training callback must register the model");
assert.ok(callback.includes("sanitizeModelMetadata") && callback.includes("registered_model_id"), "callbacks must sanitize checkpoint metadata without overwriting source model identity");
const api = readFileSync(new URL("../api/models.js", import.meta.url), "utf8");
assert.ok(api.includes("isAuthorized") && api.includes("listModels"), "model listing must be authenticated and durable");
console.log("Model registry contract tests OK");
